service: your-service-name
app: example-killian
org: aflorithmic

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: eu-west-1

functions:
  hello:
    handler: handler.hello
plugins:
  - serverless-python-requirements